/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectofinallf.frontend.reportes;

/**
 *
 * @author brandon
 */
public class DialogReportesOperacionPorSeccion extends javax.swing.JDialog {

    /**
     * Creates new form DialogReportesOperacionPorSeccion
     */
    public DialogReportesOperacionPorSeccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableOperacionCreate = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableOperacionDelete = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableOperacionUpdate = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableOperacionSelect = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableOperacionAlter = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operacion por Seccion");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        tableOperacionCreate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Operacion"
            }
        ));
        jScrollPane1.setViewportView(tableOperacionCreate);

        getContentPane().add(jScrollPane1);

        tableOperacionDelete.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Operacion"
            }
        ));
        jScrollPane2.setViewportView(tableOperacionDelete);

        getContentPane().add(jScrollPane2);

        tableOperacionUpdate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Operacion"
            }
        ));
        jScrollPane3.setViewportView(tableOperacionUpdate);

        getContentPane().add(jScrollPane3);

        tableOperacionSelect.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Operacion"
            }
        ));
        jScrollPane4.setViewportView(tableOperacionSelect);

        getContentPane().add(jScrollPane4);

        tableOperacionAlter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Operacion"
            }
        ));
        jScrollPane5.setViewportView(tableOperacionAlter);

        getContentPane().add(jScrollPane5);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tableOperacionAlter;
    private javax.swing.JTable tableOperacionCreate;
    private javax.swing.JTable tableOperacionDelete;
    private javax.swing.JTable tableOperacionSelect;
    private javax.swing.JTable tableOperacionUpdate;
    // End of variables declaration//GEN-END:variables
}
