/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectofinallf.frontend.reportes;

import com.mycompany.proyectofinallf.backend.Controlador;
import java.awt.GridLayout;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brandon
 */
public class DialogReportesTablas extends javax.swing.JDialog {

    private Controlador controlador;
    /**
     * Creates new form dialogReportesTablas
     */
    public DialogReportesTablas(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        this.controlador = controlador;
        initComponents();
        agregarTablas();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void agregarTablas() {
        this.setLayout(new GridLayout(0, 4)); // Layout para agregar JTables dinámicamente
        
        // Crear y agregar varias JTables
        for (int i = 0; i < controlador.getReportes().getTablasCreadas().size(); i++) {
            String[] columnNames = {controlador.getReportes().getTablasCreadas().get(i).getNombre()};
            Object[][] data = new Object[controlador.getReportes().getTablasCreadas().get(i).getAtributos().size()+1][1];
            for (int j = 0; j < controlador.getReportes().getTablasCreadas().get(i).getAtributos().size()+1; j++) {
                if (j == controlador.getReportes().getTablasCreadas().get(i).getAtributos().size()) {
                    data[j][0] = controlador.getReportes().getTablasCreadas().get(i).getLlaveForanea();
                } else {
                    data[j][0] = controlador.getReportes().getTablasCreadas().get(i).getAtributos().get(j)+": "+controlador.getReportes().getTablasCreadas().get(i).getTipoDatoAtributos().get(j);
                }
            }
            DefaultTableModel model = new DefaultTableModel(data, columnNames);
            JTable table = new JTable(model);
            JScrollPane scrollPane = new JScrollPane(table);
            this.add(scrollPane); // Agregar la JTable al JDialog
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tablas Encontradas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 802, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
