/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyectofinallf.frontend.reportes;

import com.mycompany.proyectofinallf.backend.Controlador;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author brandon
 */
public class DialogReportesErroresSintacticos extends javax.swing.JDialog {

    private DefaultTableModel modelo;
    private Controlador controlador;
    /**
     * Creates new form DialogReportesErroresSintacticos
     */
    public DialogReportesErroresSintacticos(java.awt.Frame parent, boolean modal, Controlador controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        if (!controlador.getReportes().getListaTokenErrorSintactico().isEmpty()) {
            agregarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "No hay errores sintacticos para mostrar.");
        }
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    private void agregarTabla() {
        Object[] datosTabla = new Object[5];
        modelo = (DefaultTableModel) tableErroresSintacticos.getModel();
        for (int i = 0; i < controlador.getReportes().getListaTokenErrorSintactico().size(); i++) {
            datosTabla[0] = controlador.getReportes().getListaTokenErrorSintactico().get(i).getLexema();
            datosTabla[1] = controlador.getReportes().getListaTokenErrorSintactico().get(i).getFila();
            datosTabla[2] = controlador.getReportes().getListaTokenErrorSintactico().get(i).getColumna();
            datosTabla[3] = controlador.getReportes().getListaTokenErrorSintactico().get(i).getDescripcion();
            datosTabla[4] = controlador.getReportes().getListaTokenErrorSintactico().get(i).getDescripcion();
            modelo.addRow(datosTabla);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableErroresSintacticos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableErroresSintacticos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableErroresSintacticos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableErroresSintacticos;
    // End of variables declaration//GEN-END:variables
}
